### ISSUE TITLE
Беларусь 

### ISSUE THREAD

**Issue by D-a-n-1-k** [DataSC3/noblack-mail#12]
При поиске номера из Беларуси вылазит ошибка:
Traceback (most recent call last):                           File "/data/data/com.termux/files/home/sherlock/PhoneInfoga/noblack-mail/noblack-mail.py", line 69, in <module>         httpweb_number.print_number_results                      File "/data/data/com.termux/files/home/sherlock/PhoneInfoga/noblack-mail/src/httpweb_number.py", line 114, in print_number_results                                                 f'{_number_data_capital.get("telcod", self.__not_found_text)}{COLOR_CODE["RESET"]}')                                     ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by megapro17** [comment]
Белоруссия

**Comment by D-a-n-1-k** [comment]
Нет такой страны

**Comment by D-a-n-1-k** [comment]
Проблема не решена

**Comment by megapro17** [comment]
Сначала правильно напиши название страны

**Comment by D-a-n-1-k** [comment]
И как же ?
