### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by BYxarek** [DataSC3/noblack-mail#24]
[1] Введите номер телефона +79833170773: #############
[~] Поиск данных..

[+] Страна: Беларусь, Республика Беларусь
[+] Город: Информация отсутствует
[+] Почтовый индекс: Информация отсутствует
[+] Код валюты: 112
Traceback (most recent call last):
  File "D:\1-SCRIPTS\probiv\noblack-mail.py", line 69, in <module>
    httpweb_number.print_number_results
  File "D:\1-SCRIPTS\probiv\src\httpweb_number.py", line 117, in print_number_results
    f'{_number_data_capital.get("telcod", self.__not_found_text)}{COLOR_CODE["RESET"]}')
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by GhostwagnerA** [comment]
ты какой код использовал?
